### ISSUE TITLE
Setting userData returns 500 

### ISSUE THREAD

**Issue by pierrelefevre** [kthcloud/go-deploy#472] opened 2024-04-10 17:43 UTC
Both update and explicit create methods are returning 500.

Tested with:

```
POST https://api.cloud.cbh.kth.se/deploy/v1/userData/onboarded 
{"data":"true"}
```

```
POST https://api.cloud.cbh.kth.se/deploy/v1/userData 
{"id":"onboarded","data":"true"}
```

POST /user***s***Data returns 404 although it is in the Swagger docs. Filed a separate issue #471

**Comment by saffronjam** [comment] 2024-04-25 12:26
I cannot reproduce, works both with admin account and test account

**Comment by saffronjam** [comment] 2024-04-28 10:33
Appears to have been fixed in previous PRs.

**Closed by saffronjam** 2024-04-28 10:33 UTC
Labels: bug, high priority

**Comment by pierrelefevre** [comment] 2024-04-29 11:54
@saffronjam Seems the issue still persists
